% Initialization of the toolbox paths
%
% Always run first this script to access all the toolbox functions

abspath = which('SdeEstimationPath');
pos = strfind(abspath, filesep); pos = pos(end);
abspath = abspath(1:pos - 1);
s = [[abspath,filesep,'Integrator;']...
    [abspath,filesep,'LLFilter;']...
    [abspath,filesep,'LLFilter',filesep,'ExpFast;']...
    [abspath,filesep,'LLFilter',filesep,'PhiKrylov;']...
    [abspath,filesep,'Innovation;']...
    [abspath,filesep,'Demos;']...
    [abspath,filesep,'Examples',filesep,'CIR;']...
    [abspath,filesep,'Examples',filesep,'ExactMul;']...
    [abspath,filesep,'Examples',filesep,'ExactAdd;']...
    [abspath,filesep,'Examples',filesep,'LinearOscillator;']...
    [abspath,filesep,'Examples',filesep,'Heston;']...
    [abspath,filesep,'Examples',filesep,'VanderPolMul;']...
    [abspath,filesep,'Examples',filesep,'VanderPolAdd;']...
    [abspath,filesep,'Examples',filesep,'FitzhughNagumo;']...
    [abspath,filesep,'Examples',filesep,'DoublePotential;']...
    [abspath,filesep,'Examples',filesep,'SIR']];
path(s,path);
